ecommerce_transforms:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: oauth
      project: enterprisedata-464016
      dataset: ecommerce_prod
      threads: 4
      timeout_seconds: 300
      location: asia-southeast1